# Numpy : Package  for multi dimensional array
  # Numpy--->numerical python

In [1]:
import numpy as np

In [2]:
#creating a array using numpy

num_list=np.array([1,2,3,4,5,6])
num_list

array([1, 2, 3, 4, 5, 6])

In [3]:
type(num_list)

numpy.ndarray

In [4]:
#creating a array  using numpy      #single dimension

new_list=[6,4,8,3,6]
arr=np.array(new_list)
type(arr)


numpy.ndarray

In [13]:
new_lst=([1,2,3],[4,5,6],[7,8,9])          #multidimensional array
new_lst
new_arr=np.array(new_lst)
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,21)         #creating a array using range 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
np.arange(5,21,3)        #(start,stop,step)

array([ 5,  8, 11, 14, 17, 20])

In [9]:
np.zeros(2)         #creating array with all zeros

array([0., 0.])

In [10]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [12]:
np.zeros((3,6),dtype=int)        #creating array with all values as zeros in multidimention

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [14]:
np.ones(5)
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
np.linspace(0,20,10)         #linear spacing

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [19]:
np.linspace(0,10,15)  

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [20]:
np.eye(7)               #identity matrix

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [21]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [23]:
np.eye(4,6,k=-2)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [24]:
np.eye(2,5,k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.random.rand(5,7)        #random values with 5rows and 7 column ranging from 0 and 1

array([[0.81130449, 0.57091116, 0.86979014, 0.06194151, 0.23444149,
        0.92557296, 0.39042089],
       [0.84224622, 0.91153812, 0.5271725 , 0.16707678, 0.28977258,
        0.32690779, 0.28265097],
       [0.3533059 , 0.75347844, 0.38866606, 0.85403366, 0.2083252 ,
        0.92359577, 0.10267584],
       [0.09803509, 0.56910482, 0.30303591, 0.91016678, 0.66336901,
        0.8002601 , 0.32847813],
       [0.34523631, 0.77642236, 0.17714231, 0.30920928, 0.4522703 ,
        0.1007168 , 0.03333578]])

In [26]:
np.random.randn(3,5)           #random values with 3 rows and 5 column with -ve and +ve values

array([[ 0.8182339 ,  0.36190972,  0.16783935, -0.11175337, -1.36383068],
       [ 1.91001126,  1.12603518,  0.03495089, -0.19994195, -0.32782604],
       [-0.38691879,  0.2010615 ,  1.44559445,  1.11205586,  0.30009426]])

In [31]:
np.random.randint(2,5)

3

In [32]:
np.random.randint(2,5,2)

array([4, 2])

In [33]:
np.random.randint(10,100,4)         #(start , end , rows)

array([56, 30, 50, 82])

In [34]:
np.random.randint(5,200,(2,3))
#gives the random values between 5 and 199 with 2 rowws and 3 column

array([[182, 129,  50],
       [103, 120,  15]])

In [37]:
array_new=np.arange(0,201)

In [39]:
array_new.min()            #returns the minimum value

0

In [41]:
array_new.argmin()

0

In [42]:
array_new.max()

200

In [43]:
array_new.argmax()        #returns index of the maximum value

200

In [44]:
array_new

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [45]:
array_new.dtype

dtype('int32')

In [46]:
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
new_arr.T        #returns the transposed value

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [54]:
A=np.random.randint(0,70,(3,4))
A

array([[46, 59, 32, 63],
       [ 8, 51, 55,  6],
       [54, 19, 13, 21]])

In [55]:
B=A=np.random.randint(0,70,(3,4))
B

array([[44, 28, 33, 21],
       [36, 55, 38,  8],
       [44, 24, 10,  6]])

In [56]:
C=A+B
C

array([[ 88,  56,  66,  42],
       [ 72, 110,  76,  16],
       [ 88,  48,  20,  12]])

In [57]:
C=A-B
C

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [58]:
D=A*B
D

array([[1936,  784, 1089,  441],
       [1296, 3025, 1444,   64],
       [1936,  576,  100,   36]])

In [60]:
sample_arr=np.arange(10,20)
sample_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [61]:
sample_arr.reshape(2,5)              #reshape the rows and columns

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [62]:
sample_arr.reshape(5,2) 

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [63]:
sample_arr[2]=21       #updating the values at given index
sample_arr

array([10, 11, 21, 13, 14, 15, 16, 17, 18, 19])

In [64]:
sample_arr[1:5]

array([11, 21, 13, 14])

In [65]:
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
new_arr[:,:1]

array([[1],
       [4],
       [7]])

In [67]:
new_arr[0:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [68]:
np.random.random(size=10)


array([0.89364148, 0.85940883, 0.88480108, 0.48386437, 0.72384143,
       0.32262342, 0.65794326, 0.89177399, 0.98870726, 0.91217203])

In [69]:
matrix=np.empty((3,3),dtype=int)

In [70]:
matrix

array([[          0,           1,           0],
       [  976301616,        1076,           0],
       [        768,         133, -1851174976]])

In [71]:
matrix[2][2]

-1851174976

In [72]:
matrix[1][2]

0

In [73]:
matrix[:]=21
matrix

array([[21, 21, 21],
       [21, 21, 21],
       [21, 21, 21]])

In [74]:
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
new_arr[0:1,1:3]         

array([[2, 3]])

In [76]:
matrix=np.full((3,3),dtype=int,fill_value=0)

In [77]:
matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [78]:
matrix.shape         #array attributes      
#returns the ros and columns

(3, 3)

In [79]:
matrix.dtype         #returns the type

dtype('int32')

In [80]:
matrix.size        #returns the number of elements

9

In [81]:
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
np.exp(new_arr)            #exponential

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [83]:
np.mean(new_arr)                #mean

5.0

In [84]:
np.var(new_arr)              #variance

6.666666666666667

In [85]:
np.std(new_arr)              #standard deviation

2.581988897471611

In [86]:
np.argmin(new_arr)

0

In [87]:
np.argmax(new_arr)

8

In [91]:
the_array=np.random.rand(3,5)
the_array

array([[0.87614835, 0.10763511, 0.97383871, 0.53720099, 0.68989995],
       [0.86561839, 0.98296479, 0.28468804, 0.9568005 , 0.22170244],
       [0.05179348, 0.46602015, 0.32233178, 0.4507942 , 0.87378814]])

In [92]:
np.round(the_array,decimals=4)

array([[0.8761, 0.1076, 0.9738, 0.5372, 0.6899],
       [0.8656, 0.983 , 0.2847, 0.9568, 0.2217],
       [0.0518, 0.466 , 0.3223, 0.4508, 0.8738]])

In [95]:
#create a null vector of size 10
X=np.random.random(size=10)
X[:]=0
X

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [99]:
#create a null vector with size 10 but fifth elemnt should be 1
X[4]=1
X

array([0., 0., 0., 0., 1., 1., 0., 0., 0., 0.])

In [101]:
#create a vector with values ranging from 10 to 65
Y=np.random.randint(10,66)
Y

63